add graceful shutdown
gosuda/go3rd pull request #3
Opened 2024-11-12 12:44 UTC by rabbitprincess

add example

2024-11-12 12:56 UTC, lemon-mint requested changes

2024-11-12 12:56 UTC, lemon-mint commented on shutdown/shutdown.go
> +	signal.Notify(sigChannel, syscall.SIGINT, syscall.SIGQUIT, syscall.SIGTERM)
Add os.Interrupt

2024-11-13 01:09 UTC, lemon-mint approved these changes

2024-11-13 01:10 UTC, merged

2024-11-13 01:39 UTC, snowmerak commented on shutdown/shutdown.go
> +	signal.Notify(sigChannel, os.Interrupt, syscall.SIGINT, syscall.SIGQUIT, syscall.SIGTERM)
use `signal.NotifyContext` instead.